[package]
name = "day8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = { version = "1.0.0", features = ["full"] }
itertools = "0.13.0"

[[bin]]
name = "day8"
path = "main.rs"
